preprocess:
  task: cross_translation # task', metavar='TASK', default="translation", choices=TASK_REGISTRY.keys(), help='task'
  src_lang: code
  tgt_lang: ~
  only_source: 0
  trainpref: ~/codexglue/code_to_code/translation/attributes/java/train #", metavar="FP", default=None, help="train file prefix"
  validpref: ~/codexglue/code_to_code/translation/attributes/java/valid #", metavar="FP", default=None, help="comma separated, valid file prefixes"
  testpref:  ~/codexglue/code_to_code/translation/attributes/java/test  #", metavar="FP", default=None, help="comma separated, test file prefixes"
  lang: java

  # bin dataset
  dataset_impl: mmap #', metavar='FORMAT', default='mmap', choices=get_available_dataset_impl(), help='output dataset implementation'
  destdir: ~/codexglue/code_to_code/retrieval/plbart/data-mmap #", metavar="DIR", default="data-bin", help="destination dir"

  only_train: 0 # if set false, generate dictionaries with additional validation datasets. e.g. neural-transformer

#  align_suffix: ~ # ", metavar="FP", default=None, help="alignment file suffix"
  threshold: 1 #", metavar="N", default=0, type=int, help="map words appearing less than threshold times to unknown"
  workers: 1 # ", metavar="N", default=1, type=int, help="number of parallel workers"