hyperparameters:
  dataloader_drop_last: True
  evaluation_strategy: "epoch"
  save_strategy: "epoch"
  logging_strategy: "epoch"
  num_train_epochs: 10
  auto_find_batch_size: True
  batch_size: 4
  logging_steps: 100
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  learning_rate: 1e-5
  lr_scheduler_type: "cosine"
  warmup_steps: 2000
  gradient_accumulation_steps: 1
  gradient_checkpointing: True
  sharded_ddp: False
  fsdp: False
  weight_decay: 0.0001
  run_name: "CodeT5-seq2seq-fine-tuned"
  ddp_find_unused_parameters: False
  fp16: True
  bf16: False
  auto_find_batch: True
  num_workers: 4
  max_prediction_length: 512
  beam_size: 5
  max_grad_norm: 5.0
  adam_epsilon : 1e-06
  load_best_model_at_end: True