from .completion_cross_entropy import CompletionCrossEntropyCriterion
from .completion_lifelong_kd_cross_entropy_loss import LifeLongKDCrossEntropyCriterion
from .completion_lifelong_topk_kd_cross_entropy_loss import LifeLongTopkKDCrossEntropyCriterion
from .reg_completion_cross_entropy import RegCompletionCrossEntropyCriterion
