hyperparameters:
  dataloader_drop_last: True
  evaluation_strategy: "epoch"
  save_strategy: "epoch"
  logging_strategy: "epoch"
  num_train_epochs: 1
  auto_find_batch_size: True
  batch_size: 4
  logging_steps: 100
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  learning_rate: 5e-6
  lr_scheduler_type: "cosine"
  warmup_steps: 2000
  gradient_accumulation_steps: 4
  gradient_checkpointing: True
  sharded_ddp: False
  fsdp: False
  weight_decay: 0.001
  run_name: "CodeT5-seq2seq-fine-tuned"
  ddp_find_unused_parameters: False
  fp16: False
  bf16: False
  auto_find_batch: True
  num_workers: 4
  max_prediction_length: 256
  beam_size: 5
  max_grad_norm: 5.0
  adam_epsilon : 1e-06
  load_best_model_at_end: True
lora:
  r: 8
  lora_alpha: 32
  lora_dropout: 0.1
adalora:
  init_r: 12
  target_r: 8
  beta1: 0.85
  beta2: 0.85
  tinit: 200
  tfinal: 1000
  deltaT: 10,
  lora_alpha: 32
  lora_dropout: 0.1
  inference_mode: False
prefixtuning:
  num_virtual_tokens: 20