from .masked_code_docstring_roberta import MaskedCodeDocstringRoberataTask
from .masked_code_docstring_unilm import MaskedCodeDocstringUnilmTask
from .masked_code_roberta import MaskedCodeRobertaTask
from .masked_lm import MaskedLMTask
from .masked_lm_huggingface import HuggingFaceMaskedLMTask
from .masked_traverse_roberta import MaskedTraverseRobertaTask