dataset:
  codexglue_text_to_code: "code_x_glue_tc_text_to_code"
  codexglue_java_to_csharp: "code_x_glue_cc_code_to_code_trans"
  codexglue_code_to_text: "code_x_glue_ct_code_to_text"
  codexglue_code_refinement: "code_x_glue_cc_code_refinement"
  APPS: "codeparrot/apps"
  openai_humaneval: "openai_humaneval"
  mbpp: "mbpp"
  repobench_python: "tianyang/repobench_python_v1.1"
  repobench_java: "tianyang/repobench_java_v1.1"
  opencoder_refinecoder: "OpenCoder-LLM/RefineCode-code-corpus-meta"
  opencoder_annealing: "OpenCoder-LLM/opc-annealing-corpus"
  opencoder_fineweb_code: "OpenCoder-LLM/opc-fineweb-code-corpus"
  opencoder_fineweb_math: "OpenCoder-LLM/opc-fineweb-math-corpus"
  opencoder_sft_stage1: "OpenCoder-LLM/opc-sft-stage1"
  opencoder_sft_stage2: "OpenCoder-LLM/opc-sft-stage2"