import glob
import networkx as nx
import pickle
import json
import os
from networkx.readwrite import json_graph
import tiktoken
from transformers import AutoTokenizer
import numpy as np
device = "cuda"

class CodeGenTokenizer:
    def __init__(self, tokenizer_raw=None):
        if tokenizer_raw is None:
            self.tokenizer = AutoTokenizer.from_pretrained("/home/wanyao/talentan/codegen2-1B_P")
        else:
            self.tokenizer = tokenizer_raw

    def tokenize(self, text):
        tensor = self.tokenizer(text, return_tensors="pt")['input_ids'][0].to(device)
        return tensor.tolist()

    def decode(self, token_ids):
        return self.tokenizer.decode(token_ids, skip_special_tokens=True)

class StarCoderTokenizer:
    def __init__(self, tokenizer_raw):
        self.tokenizer = tokenizer_raw

    def tokenize(self, text):
        return self.tokenizer.encode(text, return_tensors="pt")[0].to(device)

    def decode(self, token_ids):
        return self.tokenizer.decode(token_ids, skip_special_tokens=True)


class CodexTokenizer:
    def __init__(self):
        self.tokenizer = tiktoken.encoding_for_model("gpt-3.5-turbo-instruct")
        # self.tokenizer = tiktoken.get_encoding("p50k_base")

    def tokenize(self, text):
        # return self.tokenizer.encode(text)
        return self.tokenizer.encode(text, allowed_special={'<|endoftext|>'})

    def decode(self, token_ids):
        return self.tokenizer.decode(token_ids)


class CONSTANTS:
    """
    CONSTANTS 类用于存储项目中的常量配置。
    """
    max_hop = 5  # 最大跳数
    max_search_top_k = 10  # 最大搜索前 K 个结果
    max_statement = 10  # 最大语句数
    repo_base_dir = f"/home/wanyao/talentan/cceval/raw_data/crosscodeeval_rawdata"  # 仓库基础目录
    graph_database_save_dir = f"/home/wanyao/talentan/RepoFuse/data/context_database"  # 图数据库保存目录
    query_graph_save_dir = "/home/wanyao/talentan/RepoFuse/data/graph_based_query"  # 查询图保存目录
    dataset_dir = "/home/wanyao/talentan/cceval/data/python"  # 数据集目录
    search_res_dir = "/home/wanyao/talentan/RepoFuse/data/pythonsearch_res"
    # repos = ["devchat", "nemo_aligner", "awslabs_fortuna", "task_weaver", "huggingface_diffusers", "opendilab_ACE", 
    #          "metagpt", "apple_axlearn", "QingruZhang_AdaLoRA", "nerfstudio-project_nerfstudio", "itlemon_chatgpt4j", 
    #          "Aelysium-Group_rusty-connector", "neoforged_NeoGradle", "mybatis-flex_mybatis-flex", "Guiqu1aixi_rocketmq", 
    #          "SimonHalvdansson_Harmonic-HN", "Open-DBT_open-dbt", "QuasiStellar_custom-pixel-dungeon", "gentics_cms-oss", 
    #          "FloatingPoint-MC_MIN"]  # 仓库列表

    # repos_language = {
    #      "devchat": "python",
    #      "nemo_aligner": "python",
    #      "awslabs_fortuna": "python",
    #      "task_weaver": "python",
    #      "huggingface_diffusers": "python",
    #      "opendilab_ACE": "python",
    #      "metagpt": "python",
    #      "apple_axlearn": "python",
    #      "QingruZhang_AdaLoRA": "python",
    #      "nerfstudio-project_nerfstudio": "python",
    #      "itlemon_chatgpt4j": "java",
    #      "Aelysium-Group_rusty-connector": "java",
    #      "neoforged_NeoGradle": "java",
    #      "mybatis-flex_mybatis-flex": "java",
    #      "Guiqu1aixi_rocketmq": "java",
    #      "SimonHalvdansson_Harmonic-HN": "java",
    #      "Open-DBT_open-dbt": "java",
    #      "QuasiStellar_custom-pixel-dungeon": "java",
    #      "gentics_cms-oss": "java",
    #      "FloatingPoint-MC_MIN": "java"
    # }  # 仓库对应的编程语言

    repos = [
    "hynnsk-HP-cd48934",
    # "shijiuchen-Nodens-5589567",
    # "line-Meta-AI-Video-Similarity-Challenge-3rd-Place-Solution-b8cf098",
    # "Jackory-RPBT-dbf3696",
    # "piercefreeman-vectordb-orm-0b7fe7d",
    # "zmzhang2000-HybRank-b68bd2f",
    # "FabienRoger-concistency-lenses-6500b44",
    # "manoskary-vocsep_ijcai2023-ae7bef9",
    # "RobinSchfr-Lightning-control-for-Nanoleaf-dedf122",
    # "gabrielmbmb-kaflow-1c5ec86",
    # "BioMag-mtbi_meeg-b757aa8",
    # "OpenGSL-OpenGSL-b40738c",
    # "kraemer-lab-GRAPEVNE-1d241a8",
    # "swan-utokyo-deir-385d351",
    # "graphcore-research-unit-scaling-demo-9d9daed",
    # "JerryYLi-svitt-c8806b3",
    # "netorc-community-netorc-324512e",
    # "elementsinteractive-twyn-4517d87",
    # "EleutherAI-concept-erasure-0d4dbcb",
    # "Innocentsax-AirBnB_clone-a48e44b",
    # "microsoft-gpt-review-b0b9842",
    # "doublewinter0-auto-dns-d9e3a40",
    # "questdb-questdb-connect-459ecb6",
    # "Arbol-Project-gridded-etl-tools-320efc1",
    # "fuzzylabs-matcha-examples-c780c2e",
    # "kumitterer-matrix-gptbot-d2c6682",
    # "wm-pxel-langchain-testbench-53701f9",
    # "NREL-BuildingsBench-cc4b03d",
    # "griffinbholt-decisionmaking-code-py-e08645e",
    # "sweetice-PEER-CVPR23-142442f",
    # "aws-samples-amazon-codewhisperer-immersion-day-7b3dc66",
    # "ergodicio-adept-2c7eee5",
    # "yangbang18-ZeroNLG-bbd3f33",
    # "pawelkn-xapi-python-788a721",
    # "chainstacklabs-chainbench-177c49e",
    # "LLukas22-llm-rs-python-90e5e70",
    # "camenduru-minigpt4-439e050",
    # "ortursucceeh-Project-PhotoShare-1942d61",
    # "omron-sinicx-action-constrained-RL-benchmark-47b85fb",
    # "lambrou-SemTerm-b57ef90",
    # "cupidbow20000-cosmos20000-049e193",
    # "doccano-doccano-mini-0ef6c33",
    # "devchat-ai-devchat-a8c53d2",
    # "N00Bception-AI-Powered-5G-OpenRAN-Optimizer-a0eac7b",
    # "mobarski-aidapter-48fd7a8",
    # "slonogram-slonogram-9f86552",
    # "argus-hdps-rico-426daa0",
    # "stn-tap-jquants-336373c",
    # "yuyujunjun-RSMT-Realtime-Stylized-Motion-Transition-67c65b7",
    # "wheretrue-biobear-5be051c",
    # "mp3guy-SymE3-445731e",
    # "PatrickKalkman-python-di-2230ea4",
    # "tungduongbk-airflow-custom-plugins-f0f571d",
    # "google-lineax-4e8a44a",
    # "airdot-io-airdot-deployer-4897777",
    # "ieasybooks-tafrigh-4aece79",
    # "chatnoir-eu-web-content-extraction-benchmark-221b650",
    # "ycyy-faster-whisper-webui-fe432f8",
    # "caniko-pydantic-numpy-abcfd59",
    # "yairl-r1xbot-5323f61",
    # "diohabara-pychd-b1d0a38",
    # "iryna-kondr-scikit-llm-38ad5e9",
    # "taptorestart-forms-40b1a91",
    # "opensean-kedro-graphql-75c7dae",
    # "ezhang7423-language-control-diffusion-63cdafb",
    # "hugofloresgarcia-vampnet-6de4eeb",
    # "turboderp-exllama-a544085",
    # "run-llama-llama-lab-3364c9e",
    # "yangalan123-Amortized-Interpretability-13e3500",
    # "iqmo-org-magic_duckdb-62e6fcc",
    # "continue-revolution-sd-webui-segment-anything-5df716b",
    # "xbpeng-rl_assignments-cdb92a8",
    # "0xDebabrata-citrus-3621143",
    # "Co1Li1La1-yoshino-bot-5fe202f",
    # "jborean93-dpapi-ng-57143c3",
    # "anarchy-ai-LLM-VM-83da960",
    # "ini-multigrid-01ee811",
    # "OvO1111-EfficientSubclassLearning-afdd90e",
    # "UMEssen-matrix-scala-bd97a56",
    # "penvm-penvm-1846b0f",
    # "Adam-Vandervorst-PyBHV-ff5dcca",
    # "Priesemann-Group-nninfo-8289154",
    # "DFilyushin-habr-project-inn-0465f4f",
    # "dropreg-ChatMLM-273477a",
    # "JuniusLuo-VecLucene-8a47c91",
    # "philtabor-ProtoRL-31f81e7",
    # "thuliu-yt16-dualvector-e5ae56e",
    # "dmlc-tl2cgen-9d135f4",
    # "adobe-aepp-0e23c55",
    # "kaiko-ai-typedspark-cf5bc65",
    # "Stevenic-promptrix-py-6ed7059",
    # "david-a-jetter-pydantic-dynamo-ff0aa6d",
    # "KimmiShi-TorchDistPackage-cc385cc",
    # "xsfa-pointstorm-ede28ec",
    # "kyegomez-Blockwise-Parallel-Transformer-f849b04",
    # "neo4j-NaLLM-ca04662",
    # "meh9-game-of-life-8767f07",
    # "Significant-Gravitas-Auto-GPT-Plugins-3975893",
    # "ZhangJD-ong-MoSID-Breast-Tumor-Segmentation-from-Multi-parametric-MRI-e826e12",
    # "briandelmsft-STAT-Function-f91d421",
    # "fbdp1202-tts_data_engine-02353ab",
    # "filipporomani-whatsapp-b2c7ba4",
    # "traas-stack-holoinsight-ai-b235643",
    # "langchain-ai-kork-3ff7137",
    # "cibere-kick.py-03541c0",
    # "OSIPI-TF2.4_IVIM-MRI_CodeCollection-686d23e",
    # "tigrisdata-tigris-client-python-667d484",
    # "orsinium-labs-pytypest-80c40ed",
    # "patio-python-patio-f65bd65",
    # "pimoroni-badger2040-24d6eb6",
    # "lhenault-simpleAI-1ac4954",
    # "Zhendong-Wang-Patch-Diffusion-929b0c0",
    # "decodableco-dbt-decodable-8ef941c",
    # "pro470-Live-Save-for-Blender-3b5c1c2",
    # "somaonishi-MTR-33b87b3",
    # "AlexGidiotis-gpt-light-ae75a5e",
    # "sshh12-llm_oracle-79c8b59",
    # "knrdl-acme-ca-server-53598ad",
    # "tconbeer-textual-textarea-24fab5a",
    # "epfml-landmark-attention-111ee30",
    # "peach-db-peachdb-0fb089b",
    # "crowdgames-sturgeon-pub-a235e6d",
    # "amd-Open-Field-Health-Check-415e8a6",
    # "twopointone-stripe-integrations-ec992eb",
    # "IntelLabs-GraVi-T-08d95be",
    # "kaiokendev-superbig-be5500b",
    # "vsiegel-thoughttree-84b1498",
    # "rgbkrk-chatlab-c126c9f",
    # "jamescalam-ask-lex-plugin-3769174",
    # "roboflow-cvevals-4d29537",
    # "IBM-domain-adaptive-attribution-robustness-b4c2bee",
    # "pnkraemer-matfree-9b88279",
    # "TheStageAI-TorchIntegral-baf578b",
    # "bytewax-rt-embed-7069fc6",
    # "microsoft-seqrecord-55c8d91",
    # "lwb2099-stable_diffusion_pytorch-dbdb663",
    # "chrisli-kw-AutoTradingPlatform-e59fcfe",
    # "virtualzx-nad-easy_llm_agents-8a29505",
    # "jfc43-stratified-adv-rej-bfdc043",
    # "finopsfoundation-focus-spec-validator-7efbac5",
    # "Lightning-AI-lit-llama-da71ade",
    # "edarchimbaud-systematic-trading-a9fec02",
    # "celluloseai-sdk-9bb71fb",
    # "kadirnar-segment-anything-video-039392c",
    # "ZikangXiong-STL-Mobile-Robot-eecd396",
    # "prophecy-io-spark-ai-fd52ad1",
    # "CMU-MultiComp-Lab-CMU-MultimodalSDK-3e27d37",
    # "Facico-Chinese-Vicuna-1c4cbfc",
    # "tongyuantongyu-cycmunet-3c34dbe",
    # "shug2k-content-review-tool-93305bb",
    # "SKbarbon-swoopyui-a4fb25d",
    # "ZhengPeng7-CoSOD_fps_collection-bee3764",
    # "continuum-llms-acad-gpt-9513178",
    # "google-research-precondition-861d2da",
    # "BrianPugh-tamp-85634f4",
    # "SuperpoweredAI-task-tree-agent-45b0a49",
    # "fritzsedlazeck-Spectre-01b8ed5",
    # "thismlguy-code-genie-58f789c",
    # "Tlntin-ChatGLM2-6B-TensorRT-bd55117",
    # "sebastienrousseau-pain001-86a271f",
    # "IBM-auto-contrastive-generation-4874a25",
    # "willleeney-ugle-7cfe1b3",
    # "gorarakelyan-langchain-chatbot-72a8678",
    # "edsaav-nail-64acdc6",
    # "ycc140-fastapi_messaging-bed8c86",
    # "RangiLyu-llama.mmengine-1887d56",
    # "hbqjzx-wxxiaozhi-dfc4a65",
    # "entbappy-cnnClassifier-acadb8a",
    # "nicolasebastianelli-speech-ai-323473b",
    # "Kubenew-ChaosGPT-2c40353",
    # "steklyashka33-Minecraft-Mod-Translator-92de64d",
    # "BlueBrain-Currentscape-29753e8",
    # "pygfx-gfxmorph-0a3a9d9",
    # "happen2me-subgraph-retrieval-toolkit-5655cb3",
    # "mlfoundations-dataset2metadata-a673a83",
    # "Srameo-DNF-974080a",
    # "bazingagin-npc_gzip-928659e",
    # "JunbongJang-contour-tracking-1219b66",
    # "gdsfactory-kplugins-7a5f7b4",
    # "slawekradzyminski-personal-ai-assistant-2736d10",
    # "alex-zaikman-fastapi-postgres-tmpl-cc200aa",
    # "minyoungg-vqtorch-d0022ea",
    # "clear-nus-NCDSSM-7212bba",
    # "Cerlancism-faster-whisper-webui-884f5fd",
    # "Sygil-Dev-muse-maskgit-pytorch-7d7c00c",
    # "GoogleCloudPlatform-alloydb-python-connector-a397ea7",
    # "FizzleDorf-AIT-ad34668",
    # "jtext-103-jddb-077b729",
    # "GenBench-genbench_cbt-caa63fb",
    # "opticore-netbox-nornir-3cd275e",
    # "blurry-dev-blurry-1d20aad",
    # "congtuong-docile-44e4fce",
    # "uripeled2-llm-client-sdk-66af541",
    # "ches-001-metatune-278c315",
    # "dbt-labs-dbt-meshify-a11e507",
    # "llmapi-io-llmapi-server-cdae9ca",
    # "facebookresearch-AudioDec-9b49838",
    # "Herta-villa-Herta-villa-SDK-c862c3b",
    # "build-aau-lcabyg_web_api_doc-b001c5d",
    # "34j-boost-loss-ff08630",
    # "profcomff-social-api-d0b645b",
    # "gdsfactory-gf180-3407e7a",
    # "GChristensen-deepfloyd_if_lab-4644b93",
    # "mboot-github-WhoisDomain-0b5dbb3",
    # "livekit-client-sdk-python-b14fa6c",
    # "EmbedInAI-EmbedInDB-b2d7852",
    # "nobu-g-JGLUE-evaluation-scripts-2a39b31",
    # "lskyset-priconne-asset-extractor-3d54812",
    # "blurgyy-jaxngp-adbe49e",
    # "dmemsys-SMART-dc4de6f",
    # "apple-ml-tract-ad25296",
    # "ChuloAI-BrainChulo-cacf3ac",
    # "alteryx-locust-grasshopper-632db06",
    # "davidmaamoaix-singleline-311d35f",
    # "weaweawe01-luajit_decompile-2b32d4b",
    # "KyGao-ABGNN-1832ca7",
    # "husisy-arxiv-gpt-ef98efb",
    # "ml-opt-lab-sdmgrad-86963c6",
    # "havenhq-haven-fa692f2",
    # "AICPS-RS2G-b4e985f",
    # "salesforce-AuditNLG-c473044",
    # "sauljabin-kayak-9fc4a65",
    # "Zhang-Zhiyuan-zzy-hotpot-3a13089",
    # "lucmos-powermanim-1bcf62a",
    # "tricktreat-DiffusionNER-cb095cd",
    # "janghyuk-choi-slot-attention-lightning-2993443",
    # "light1726-BetaVAE_VC-08902f2",
    # "OUIsolutions-CWebStudio-633d7c6",
    # "ryongithub-GatedPromptTuning-1de14b5",
    # "yoheinakajima-babyagi-d10b08c",
    # "FrancescoSaverioZuppichini-LinkedInGPT-e0c1552",
    # "Quantomatic-zxlive-c7b5c28",
    # "Fsoft-AIC-Class-Based-Influence-Functions-b957b78",
    # "drubinstein-python-compose-f3ab44c",
    # "memew1se-OpenRSS-f7b766b",
    # "leggedrobotics-rayen-2ac7086",
    # "mraniki-dxsp-71b0c1e",
    # "HiPer0-HiPer-48a2f6e",
    # "isayahc-Semi-Automated-Youtube-Channel-80b0201",
    # "DMSintalor-OJ-Be-f04ae6e",
    # "metalbobinou-python-ListComparator-00b6794",
    # "pp-mo-ncdata-555ff35",
    # "MatteoSalvatori-INCE-23e589c",
    # "NVIDIA-ISAAC-ROS-ros2_benchmark-d7725da",
    # "3dlg-hcvc-M3DRef-CLIP-420419e",
    # "hyperliquid-dex-hyperliquid-python-sdk-6ddfbfb",
    # "evalplus-evalplus-8b713cd",
    # "ml-research-SLASH-8d0f42d",
    # "davisyoshida-qax-34f0905",
    # "freddyaboulton-gradio-tools-f0297df",
    # "paulromano-endf-python-745bbb5",
    # "OHDSI-Apollo-57fa612",
    # "nccgroup-libslub-7732a54",
    # "teelinsan-parallel-decoding-b16a009",
    # "hcmlab-GANonymization-a917aba",
    # "v-mikhaylov-tfold-release-e2bae1f",
    # "nvidia-holoscan-holoscan-test-suite-e7a809d",
    # "AntonOsika-gpt-engineer-fc80507",
    # "bswck-configzen-42ed40f",
    # "egrinstein-gnn_ssl-74c7b5a",
    # "melMass-comfy_mtb-3b07984",
    # "log10-io-log10-d605f37",
    # "eimenhmdt-autoresearcher-5235ee7",
    # "Gage-Technologies-embedding-server-6b66d47",
    # "DAMO-NLP-SG-MT-LLaMA-c72f7db",
    # "paulpanwang-Cas6D-245489d",
    # "ashi-ta-speechGLUE-724cf40",
    # "tarsil-databasez-01b23b0",
    # "K024-chatglm-q-eab6472",
    # "dishb-hive-f0bf4b5",
    # "Mattie-chatsnack-94305b2",
    # "usecakework-async-backend-c288d0b",
    # "Spawning-Inc-datadiligence-9e949d2",
    # "danilonumeroso-dar-64e8631",
    # "continuum-llms-chatgpt-memory-ee08ccc",
    # "danyi1212-celery-insights-a742653",
    # "hyp3rd-telegram-discord-bridge-24fa2fb",
    # "babylm-baseline-pretraining-43acf2a",
    # "f-inc-dynamic-e4036a7",
    # "leandl-wvalidate-8cb9603",
    # "bufbuild-protovalidate-python-2eee9ba",
    # "phac-nml-rebar-aef5b97",
    # "celyes-checkr-dabd705",
    # "deep-diver-TFX-WandB-05c63c4",
    # "irgolic-AutoPR-10e2891",
    # "czczup-GPTrans-1f6f651",
    # "xrcyz-dpg-swisscontrols-9412ad4",
    # "aiplan4eu-UP4ROS-59c1358",
    # "open-mmlab-Multimodal-GPT-9c73e47",
    # "inWeb3ai-chatWeb3-cf1c933",
    # "dichem-django-excel-report-686e1da",
    # "yotakayama-STLCCP-edcfad4",
    # "Materials-Data-Science-and-Informatics-somesy-a47ca93",
    # "operand-agency-07b1076",
    # "SAIC-iSmart-API-saic-python-client-29b99ad",
    # "mihirh19-todo_web_app-fed9043",
    # "wxian3-NeuroLens-380d68c",
    # "sonic-net-sonic-platform-vpp-e8483f4",
    # "gitguesser-gitguesser-297d633",
    # "dory111111-Pengenuity-297d9ee",
    # "microsoft-DPSDA-79f0868",
    # "beidongjiedeguang-openai-forward-c2c2757",
    # "AdaptChat-adapt.py-9e079c0",
    # "ZJUM3-LLMEval_RCC-a731888",
    # "ironwoodcall-TagTracker-bb1e3d9",
    # "deepmatterltd-rdfreader-a811645",
    # "SilicalNZ-TapTitans2py-0d5409d",
    # "CircuitSacul-io-775ac7c",
    # "valentingol-cliconfig-c772180",
    # "callowayproject-bump-my-version-0cf1cb5",
    # "rmihaylov-falcontune-6bd029e",
    # "last-war-photoshare-fastapi-67888ff",
    # "crypto-jobs-fyi-crawler-b0596e6",
    # "pycob-pyvibe-1c1c138",
    # "motherofcoconuts-async-dramatiq-b9512a1",
    # "ch3njust1n-generative-api-a2ac928",
    # "colindecourt-darod-ab4878e",
    # "uezo-aiavatarkit-37d28f7",
    # "tricktreat-PromptNER-3857235",
    # "viper-framework-viper2-bd8aa34",
    # "oriyor-reasoning-on-cots-9ae01ce",
    # "jfamestad-TexasHoldemAgents-a171a13",
    # "lxjmaster-ja3requests-90a33e6",
    # "nyaarium-blender-nyaatools-4fc69af",
    # "amazon-science-random-tma-43df305",
    # "RTIInternational-teehr-2bd727d",
    # "yuvalkirstain-PickScore-5fa69e8",
    # "Mikanwolfe-Kuro-55d0744",
    # "vectara-vectara-ingest-0a867f1",
    # "Textualize-frogmouth-965b92e",
    # "francoismdj-netbox-kea-dhcp-f53d9df",
    # "radar-research-lab-MFGLib-7f12f9d",
    # "techonomydev-django-crispy-tableselect-e2e7016",
    # "20171130-llmux-249dcdb",
    # "quarkslab-tritondse-9805288",
    # "javiber-scrat-748926a",
    # "stac-utils-stac-asset-a83c660",
    # "mecene-studio-debugGpt-20e9b61",
    # "PatrickKalkman-python-eda-e98886c",
    # "Stardust-hyx-Instruction_Tuning-62e36d0",
    # "sprite-neu-SPREAD-API-a2ee03a",
    # "Genentech-walk-jump-3cfaa37",
    # "huanranchen-EnergyBasedGenerativeModel-ad5989a",
    # "CassioML-cassio-7953897",
    # "brown-ivl-Cafi-Net-6171499",
    # "Ying1123-llm-caching-multiplexing-2dc7e69",
    # "Typing-Monkeys-complex-network-link-prediction-cf69190",
    # "eloimoliner-BABE-777b624",
    # "ddPn08-rvc-webui-c4a12a8",
    # "RobertoCorti-gptravel-bcf49dd",
    # "tmori-generative-agents-81cabfd",
    # "microsoft-deep-language-networks-e7accd0",
    # "SEIAROTg-autobean-format-2a51179",
    # "algorand-conduit-bcb54fd",
    # "theneonwhale-frt-photo-share-6659afb",
    # "heng840-All_pipeline_Information_Extraction-e94dd96",
    # "UKPLab-nlpeer-f81f4bb",
    # "utiasDSL-fmpc_socp-de13764",
    # "chunmeifeng-FedPR-f5c3e67",
    # "imaginationtech-constrainedrandom-db5b49a",
    # "entangled-entangled.py-4dcbb63",
    # "bxdoan-venom-auto-da0fcfa",
    # "Kamilfo-Developer-alice-sleepy-helper-skill-febf9f7",
    # "obahamonde-aiofauna-67993d2",
    # "ingra14m-mipnerf360-pytorch-bfc1e77",
    # "fivexl-terraform-aws-sso-elevator-fd46f09",
    # "s41m0n-enid-227634a",
    # "jiangjiechen-uncommongen-7d1c76e",
    # "Panzer-Jack-ChatGLM_VITS_For_QQ-Rob-5b11f0a",
    # "brdav-cma-fdae11a",
    # "diptanu-indexify-216ecf2",
    # "rosemary666-chatgpt-3adfb2d",
    # "graphcore-PopTransformer-1314598",
    # "pitaya1001-hta-c83dc5c",
    # "speedb-io-log-parser-d600b0e",
    # "kiran94-prfiesta-c37e012",
    # "Hxyou-IdealGPT-54f5acf",
    # "dpasse-extr-f695d3c",
    # "krishnaik06-Chicken-Disease-Classification-Projects-d0f5e13",
    # "yarrow-id-diagrams-9cbd653",
    # "voneiden-ocp-freecad-cam-4813dc9",
    # "Donnype-xtdb-py-fc89588",
    # "jannerm-ddpo-f0b6ca7",
    # "ppoitier-sign-language-tools-46eadf9",
    # "yanqingmen-ask-api-69926aa",
    # "canpool-QxRibbon-4bbd7f5",
    # "axelmunch-laser-tag-38f6fc0",
    # "SolarisNeko-suger-python-67383eb",
    # "heshuting555-PAP-FZS3D-e3fc6cb",
    # "quarkslab-pastis-d790def",
    # "Open-Swarm-Net-GPT-Swarm-edfddce",
    # "gabacode-chatGPDP-4701532",
    # "kabeer11000-autollm-53e7404",
    # "libsql-libsql-client-py-484c7d3",
    # "OpenGVLab-VideoMAEv2-9492db0",
    # "liuzuxin-OSRL-6ede2c2",
    # "knexer-ai-storyteller-86da1d3",
    # "pomponchik-instld-1df14ba",
    # "OpenAccess-AI-Collective-axolotl-2c37bf6",
    # "gnbonney-SymLogos-08a26af",
    # "solo-spice-sospice-64c941b",
    # "odtuyzt-chrono-kit-923b505",
    # "david-stan-dagfed-chain-0a60a23",
    # "NoFish-528-encodec-pytorch-9c2f4a0",
    # "hq0709-Depth-NeuS-49d93d4",
    # "chrisrude-oobabot-fa234d6",
    # "marcpage-pylavi-90a3e81",
    # "NKI-AI-STAPLER-bf072e9",
    # "JohnnyIrvin-shell-craft-26a7af7",
    # "Jason-Qiu-MultiSum_model-c4c58dd",
    # "esnya-lm-talkbot-f072b85",
    # "smpanaro-more-ane-transformers-d5aec6f",
    # "slewie-HypONIC-5b95063",
    # "deadblue-py115-ecdcb93",
    # "IntelligenzaArtificiale-Free-Auto-GPT-095e991",
    # "appsignal-appsignal-python-5a0cfa9",
    # "chunbolang-R2Net-856e1cc",
    # "geoffwhittington-meshtastic-matrix-relay-ffe969f",
    # "satyapravin-Deribit-Option-Arb-c6fead7",
    # "amazon-science-ope-learn-action-embeddings-4ff26bf",
    # "flatironinstitute-mountainsort5-3e85076",
    # "reko-beep-hsr-data-c73208a",
    # "kabachuha-sd-webui-text2video-20ead10",
    # "AlphaDinosaur89-glang-de75a3e",
    # "iuiaoin-wechat-gptbot-b379085",
    # "Adeon18-Mori-Bazius-Backend-f33b8ba",
    # "medley56-space_packet_parser-d94290c",
    # "KTH-FlowAI-DeepReinforcementLearning_RayleighBenard2D_Control-d1a8dd6",
    # "maxvanspengler-hyperbolic_learning_library-f6cfca3",
    # "scottjiao-SlotGAT_ICML23-4aa4583",
    # "Donkie-Spoolman-2fcfc38",
    # "vetka925-llms-lora-8bit-4bit-finetuning-lit-eb1b149",
    # "adrienbrignon-mkdocs-exporter-bdbd7b5",
    # "thb1314-maskrcnn-tensorrt-1bafff6",
    # "kit-cel-mokka-8a555d9",
    # "HelsinkiUniCollab-WeatherBasedRecommender-cfd21fd",
    # "CPJKU-paow-c8ead3d",
    # "opticore-netbox-celery-553cbe6",
    # "probcomp-LLaMPPL-56ef219",
    # "Cybereason-eztw-94a0ae9",
    # "bytedance-uss-0c15a08",
    # "Thetacz-nautobot-plugin-device-resources-4caef01",
    # "LeoMo-27-FastAPI-template-f19c7aa",
    # "janvarev-OneRingTranslator-e4dab8d",
    # "snu-mllab-Efficient-CNN-Depth-Compression-2828ae8",
    # "LineIndent-material_design_flet-bca5bd8",
    # "SindiLab-scANNA-b65b3d8",
    # "awslabs-decode-answer-logical-form-08d5790",
    # "ZX-Yin-ms-nerf-9009137",
    # "bharatsubedi-PARseq_torch-8ffcb95",
    # "maybelinot-yamx-5e304a5",
    # "Josh-XT-AGiXT-828a01d",
    # "EdwardLeeLPZ-PowerBEV-7ead4ce",
    # "eugenos-programos-Own-language-with-LLVM-lite-c8b9e08",
    # "eurobios-scb-acrocord-94aeb5e",
    # "jdum-asciinema-scene-82f586d",
    # "bond-anton-BDPotentiometer-872a7e2",
    # "StigLidu-AutoTruss-ffb5707",
    # "datasig-ac-uk-RoughPy-fbd9016",
    # "YangXiaocui1215-GMP-d3cb04f",
    # "ansys-pyaedt-toolkit-template-73b2fc9",
    # "krishnaik06-Text-Summarization-NLP-Project-3308112",
    # "leonelhs-face-shine-8f21b90",
    # "CERT-EDF-generaptor-e71eb4c",
    # "chrisdewa-ardilla-312a373",
    # "deep-diver-PingPong-7ace26b",
    # "wolfhoundgelert-xman-1da4d2d",
    # "jiggy-ai-jiggybase-068b82b",
    # "vladkens-twscrape-4f2ee7f",
    # "remixer-dec-botality-ii-f8402d5",
    # "dSupertramp-PubGPT-253ec52"
]

    repos_language = {
    # "sweetice-PEER-CVPR23-142442f": "python",
    # "google-lineax-4e8a44a": "python",
    "hynnsk-HP-cd48934": "python",
    # "shijiuchen-Nodens-5589567": "python",
    # "line-Meta-AI-Video-Similarity-Challenge-3rd-Place-Solution-b8cf098": "python",
    # "Jackory-RPBT-dbf3696": "python",
    # "piercefreeman-vectordb-orm-0b7fe7d": "python",
    # "zmzhang2000-HybRank-b68bd2f": "python",
    # "FabienRoger-concistency-lenses-6500b44": "python",
    # "manoskary-vocsep_ijcai2023-ae7bef9": "python",
    # "RobinSchfr-Lightning-control-for-Nanoleaf-dedf122": "python",
    # "gabrielmbmb-kaflow-1c5ec86": "python",
    # "BioMag-mtbi_meeg-b757aa8": "python",
    # "OpenGSL-OpenGSL-b40738c": "python",
    # "kraemer-lab-GRAPEVNE-1d241a8": "python",
    # "swan-utokyo-deir-385d351": "python",
    # "graphcore-research-unit-scaling-demo-9d9daed": "python",
    # "JerryYLi-svitt-c8806b3": "python",
    # "netorc-community-netorc-324512e": "python",
    # "elementsinteractive-twyn-4517d87": "python",
    # "EleutherAI-concept-erasure-0d4dbcb": "python",
    # "Innocentsax-AirBnB_clone-a48e44b": "python",
    # "microsoft-gpt-review-b0b9842": "python",
    # "doublewinter0-auto-dns-d9e3a40": "python",
    # "questdb-questdb-connect-459ecb6": "python",
    # "Arbol-Project-gridded-etl-tools-320efc1": "python",
    # "fuzzylabs-matcha-examples-c780c2e": "python",
    # "kumitterer-matrix-gptbot-d2c6682": "python",
    # "wm-pxel-langchain-testbench-53701f9": "python",
    # "NREL-BuildingsBench-cc4b03d": "python",
    # "griffinbholt-decisionmaking-code-py-e08645e": "python",
    # "aws-samples-amazon-codewhisperer-immersion-day-7b3dc66": "python",
    # "ergodicio-adept-2c7eee5": "python",
    # "yangbang18-ZeroNLG-bbd3f33": "python",
    # "pawelkn-xapi-python-788a721": "python",
    # "chainstacklabs-chainbench-177c49e": "python",
    # "LLukas22-llm-rs-python-90e5e70": "python",
    # "camenduru-minigpt4-439e050": "python",
    # "ortursucceeh-Project-PhotoShare-1942d61": "python",
    # "omron-sinicx-action-constrained-RL-benchmark-47b85fb": "python",
    # "lambrou-SemTerm-b57ef90": "python",
    # "cupidbow20000-cosmos20000-049e193": "python",
    # "doccano-doccano-mini-0ef6c33": "python",
    # "devchat-ai-devchat-a8c53d2": "python",
    # "N00Bception-AI-Powered-5G-OpenRAN-Optimizer-a0eac7b": "python",
    # "mobarski-aidapter-48fd7a8": "python",
    # "slonogram-slonogram-9f86552": "python",
    # "argus-hdps-rico-426daa0": "python",
    # "stn-tap-jquants-336373c": "python",
    # "yuyujunjun-RSMT-Realtime-Stylized-Motion-Transition-67c65b7": "python",
    # "wheretrue-biobear-5be051c": "python",
    # "mp3guy-SymE3-445731e": "python",
    # "PatrickKalkman-python-di-2230ea4": "python",
    # "tungduongbk-airflow-custom-plugins-f0f571d": "python",
    # "airdot-io-airdot-deployer-4897777": "python",
    # "ieasybooks-tafrigh-4aece79": "python",
    # "chatnoir-eu-web-content-extraction-benchmark-221b650": "python",
    # "ycyy-faster-whisper-webui-fe432f8": "python",
    # "caniko-pydantic-numpy-abcfd59": "python",
    # "yairl-r1xbot-5323f61": "python",
    # "diohabara-pychd-b1d0a38": "python",
    # "iryna-kondr-scikit-llm-38ad5e9": "python",
    # "taptorestart-forms-40b1a91": "python",
    # "opensean-kedro-graphql-75c7dae": "python",
    # "ezhang7423-language-control-diffusion-63cdafb": "python",
    # "hugofloresgarcia-vampnet-6de4eeb": "python",
    # "turboderp-exllama-a544085": "python",
    # "run-llama-llama-lab-3364c9e": "python",
    # "yangalan123-Amortized-Interpretability-13e3500": "python",
    # "iqmo-org-magic_duckdb-62e6fcc": "python",
    # "continue-revolution-sd-webui-segment-anything-5df716b": "python",
    # "xbpeng-rl_assignments-cdb92a8": "python",
    # "0xDebabrata-citrus-3621143": "python",
    # "Co1Li1La1-yoshino-bot-5fe202f": "python",
    # "jborean93-dpapi-ng-57143c3": "python",
    # "anarchy-ai-LLM-VM-83da960": "python",
    # "ini-multigrid-01ee811": "python",
    # "OvO1111-EfficientSubclassLearning-afdd90e": "python",
    # "UMEssen-matrix-scala-bd97a56": "python",
    # "penvm-penvm-1846b0f": "python",
    # "Adam-Vandervorst-PyBHV-ff5dcca": "python",
    # "Priesemann-Group-nninfo-8289154": "python",
    # "DFilyushin-habr-project-inn-0465f4f": "python",
    # "dropreg-ChatMLM-273477a": "python",
    # "JuniusLuo-VecLucene-8a47c91": "python",
    # "philtabor-ProtoRL-31f81e7": "python",
    # "thuliu-yt16-dualvector-e5ae56e": "python",
    # "dmlc-tl2cgen-9d135f4": "python",
    # "adobe-aepp-0e23c55": "python",
    # "kaiko-ai-typedspark-cf5bc65": "python",
    # "Stevenic-promptrix-py-6ed7059": "python",
    # "david-a-jetter-pydantic-dynamo-ff0aa6d": "python",
    # "KimmiShi-TorchDistPackage-cc385cc": "python",
    # "xsfa-pointstorm-ede28ec": "python",
    # "kyegomez-Blockwise-Parallel-Transformer-f849b04": "python",
    # "neo4j-NaLLM-ca04662": "python",
    # "meh9-game-of-life-8767f07": "python",
    # "Significant-Gravitas-Auto-GPT-Plugins-3975893": "python",
    # "ZhangJD-ong-MoSID-Breast-Tumor-Segmentation-from-Multi-parametric-MRI-e826e12": "python",
    # "briandelmsft-STAT-Function-f91d421": "python",
    # "fbdp1202-tts_data_engine-02353ab": "python",
    # "filipporomani-whatsapp-b2c7ba4": "python",
    # "traas-stack-holoinsight-ai-b235643": "python",
    # "langchain-ai-kork-3ff7137": "python",
    # "cibere-kick.py-03541c0": "python",
    # "OSIPI-TF2.4_IVIM-MRI_CodeCollection-686d23e": "python",
    # "tigrisdata-tigris-client-python-667d484": "python",
    # "orsinium-labs-pytypest-80c40ed": "python",
    # "patio-python-patio-f65bd65": "python",
    # "pimoroni-badger2040-24d6eb6": "python",
    # "lhenault-simpleAI-1ac4954": "python",
    # "Zhendong-Wang-Patch-Diffusion-929b0c0": "python",
    # "decodableco-dbt-decodable-8ef941c": "python",
    # "pro470-Live-Save-for-Blender-3b5c1c2": "python",
    # "somaonishi-MTR-33b87b3": "python",
    # "AlexGidiotis-gpt-light-ae75a5e": "python",
    # "sshh12-llm_oracle-79c8b59": "python",
    # "knrdl-acme-ca-server-53598ad": "python",
    # "tconbeer-textual-textarea-24fab5a": "python",
    # "epfml-landmark-attention-111ee30": "python",
    # "peach-db-peachdb-0fb089b": "python",
    # "crowdgames-sturgeon-pub-a235e6d": "python",
    # "amd-Open-Field-Health-Check-415e8a6": "python",
    # "twopointone-stripe-integrations-ec992eb": "python",
    # "IntelLabs-GraVi-T-08d95be": "python",
    # "kaiokendev-superbig-be5500b": "python",
    # "vsiegel-thoughttree-84b1498": "python",
    # "rgbkrk-chatlab-c126c9f": "python",
    # "jamescalam-ask-lex-plugin-3769174": "python",
    # "roboflow-cvevals-4d29537": "python",
    # "IBM-domain-adaptive-attribution-robustness-b4c2bee": "python",
    # "pnkraemer-matfree-9b88279": "python",
    # "TheStageAI-TorchIntegral-baf578b": "python",
    # "bytewax-rt-embed-7069fc6": "python",
    # "microsoft-seqrecord-55c8d91": "python",
    # "lwb2099-stable_diffusion_pytorch-dbdb663": "python",
    # "chrisli-kw-AutoTradingPlatform-e59fcfe": "python",
    # "virtualzx-nad-easy_llm_agents-8a29505": "python",
    # "jfc43-stratified-adv-rej-bfdc043": "python",
    # "finopsfoundation-focus-spec-validator-7efbac5": "python",
    # "Lightning-AI-lit-llama-da71ade": "python",
    # "edarchimbaud-systematic-trading-a9fec02": "python",
    # "celluloseai-sdk-9bb71fb": "python",
    # "kadirnar-segment-anything-video-039392c": "python",
    # "ZikangXiong-STL-Mobile-Robot-eecd396": "python",
    # "prophecy-io-spark-ai-fd52ad1": "python",
    # "CMU-MultiComp-Lab-CMU-MultimodalSDK-3e27d37": "python",
    # "Facico-Chinese-Vicuna-1c4cbfc": "python",
    # "tongyuantongyu-cycmunet-3c34dbe": "python",
    # "shug2k-content-review-tool-93305bb": "python",
    # "SKbarbon-swoopyui-a4fb25d": "python",
    # "ZhengPeng7-CoSOD_fps_collection-bee3764": "python",
    # "continuum-llms-acad-gpt-9513178": "python",
    # "google-research-precondition-861d2da": "python",
    # "BrianPugh-tamp-85634f4": "python",
    # "SuperpoweredAI-task-tree-agent-45b0a49": "python",
    # "fritzsedlazeck-Spectre-01b8ed5": "python",
    # "thismlguy-code-genie-58f789c": "python",
    # "Tlntin-ChatGLM2-6B-TensorRT-bd55117": "python",
    # "sebastienrousseau-pain001-86a271f": "python",
    # "IBM-auto-contrastive-generation-4874a25": "python",
    # "willleeney-ugle-7cfe1b3": "python",
    # "gorarakelyan-langchain-chatbot-72a8678": "python",
    # "edsaav-nail-64acdc6": "python",
    # "ycc140-fastapi_messaging-bed8c86": "python",
    # "RangiLyu-llama.mmengine-1887d56": "python",
    # "hbqjzx-wxxiaozhi-dfc4a65": "python",
    # "entbappy-cnnClassifier-acadb8a": "python",
    # "nicolasebastianelli-speech-ai-323473b": "python",
    # "Kubenew-ChaosGPT-2c40353": "python",
    # "steklyashka33-Minecraft-Mod-Translator-92de64d": "python",
    # "BlueBrain-Currentscape-29753e8": "python",
    # "pygfx-gfxmorph-0a3a9d9": "python",
    # "happen2me-subgraph-retrieval-toolkit-5655cb3": "python",
    # "mlfoundations-dataset2metadata-a673a83": "python",
    # "Srameo-DNF-974080a": "python",
    # "bazingagin-npc_gzip-928659e": "python",
    # "JunbongJang-contour-tracking-1219b66": "python",
    # "gdsfactory-kplugins-7a5f7b4": "python",
    # "slawekradzyminski-personal-ai-assistant-2736d10": "python",
    # "alex-zaikman-fastapi-postgres-tmpl-cc200aa": "python",
    # "minyoungg-vqtorch-d0022ea": "python",
    # "clear-nus-NCDSSM-7212bba": "python",
    # "Cerlancism-faster-whisper-webui-884f5fd": "python",
    # "Sygil-Dev-muse-maskgit-pytorch-7d7c00c": "python",
    # "GoogleCloudPlatform-alloydb-python-connector-a397ea7": "python",
    # "FizzleDorf-AIT-ad34668": "python",
    # "jtext-103-jddb-077b729": "python",
    # "GenBench-genbench_cbt-caa63fb": "python",
    # "opticore-netbox-nornir-3cd275e": "python",
    # "blurry-dev-blurry-1d20aad": "python",
    # "congtuong-docile-44e4fce": "python",
    # "uripeled2-llm-client-sdk-66af541": "python",
    # "ches-001-metatune-278c315": "python",
    # "dbt-labs-dbt-meshify-a11e507": "python",
    # "llmapi-io-llmapi-server-cdae9ca": "python",
    # "facebookresearch-AudioDec-9b49838": "python",
    # "Herta-villa-Herta-villa-SDK-c862c3b": "python",
    # "build-aau-lcabyg_web_api_doc-b001c5d": "python",
    # "34j-boost-loss-ff08630": "python",
    # "profcomff-social-api-d0b645b": "python",
    # "gdsfactory-gf180-3407e7a": "python",
    # "GChristensen-deepfloyd_if_lab-4644b93": "python",
    # "mboot-github-WhoisDomain-0b5dbb3": "python",
    # "livekit-client-sdk-python-b14fa6c": "python",
    # "EmbedInAI-EmbedInDB-b2d7852": "python",
    # "nobu-g-JGLUE-evaluation-scripts-2a39b31": "python",
    # "lskyset-priconne-asset-extractor-3d54812": "python",
    # "blurgyy-jaxngp-adbe49e": "python",
    # "dmemsys-SMART-dc4de6f": "python",
    # "apple-ml-tract-ad25296": "python",
    # "ChuloAI-BrainChulo-cacf3ac": "python",
    # "alteryx-locust-grasshopper-632db06": "python",
    # "davidmaamoaix-singleline-311d35f": "python",
    # "weaweawe01-luajit_decompile-2b32d4b": "python",
    # "KyGao-ABGNN-1832ca7": "python",
    # "husisy-arxiv-gpt-ef98efb": "python",
    # "ml-opt-lab-sdmgrad-86963c6": "python",
    # "havenhq-haven-fa692f2": "python",
    # "AICPS-RS2G-b4e985f": "python",
    # "salesforce-AuditNLG-c473044": "python",
    # "sauljabin-kayak-9fc4a65": "python",
    # "Zhang-Zhiyuan-zzy-hotpot-3a13089": "python",
    # "lucmos-powermanim-1bcf62a": "python",
    # "tricktreat-DiffusionNER-cb095cd": "python",
    # "janghyuk-choi-slot-attention-lightning-2993443": "python",
    # "light1726-BetaVAE_VC-08902f2": "python",
    # "OUIsolutions-CWebStudio-633d7c6": "python",
    # "ryongithub-GatedPromptTuning-1de14b5": "python",
    # "yoheinakajima-babyagi-d10b08c": "python",
    # "FrancescoSaverioZuppichini-LinkedInGPT-e0c1552": "python",
    # "Quantomatic-zxlive-c7b5c28": "python",
    # "Fsoft-AIC-Class-Based-Influence-Functions-b957b78": "python",
    # "drubinstein-python-compose-f3ab44c": "python",
    # "memew1se-OpenRSS-f7b766b": "python",
    # "leggedrobotics-rayen-2ac7086": "python",
    # "mraniki-dxsp-71b0c1e": "python",
    # "HiPer0-HiPer-48a2f6e": "python",
    # "isayahc-Semi-Automated-Youtube-Channel-80b0201": "python",
    # "DMSintalor-OJ-Be-f04ae6e": "python",
    # "metalbobinou-python-ListComparator-00b6794": "python",
    # "pp-mo-ncdata-555ff35": "python",
    # "MatteoSalvatori-INCE-23e589c": "python",
    # "NVIDIA-ISAAC-ROS-ros2_benchmark-d7725da": "python",
    # "3dlg-hcvc-M3DRef-CLIP-420419e": "python",
    # "hyperliquid-dex-hyperliquid-python-sdk-6ddfbfb": "python",
    # "evalplus-evalplus-8b713cd": "python",
    # "ml-research-SLASH-8d0f42d": "python",
    # "davisyoshida-qax-34f0905": "python",
    # "freddyaboulton-gradio-tools-f0297df": "python",
    # "paulromano-endf-python-745bbb5": "python",
    # "OHDSI-Apollo-57fa612": "python",
    # "nccgroup-libslub-7732a54": "python",
    # "teelinsan-parallel-decoding-b16a009": "python",
    # "hcmlab-GANonymization-a917aba": "python",
    # "v-mikhaylov-tfold-release-e2bae1f": "python",
    # "nvidia-holoscan-holoscan-test-suite-e7a809d": "python",
    # "AntonOsika-gpt-engineer-fc80507": "python",
    # "bswck-configzen-42ed40f": "python",
    # "egrinstein-gnn_ssl-74c7b5a": "python",
    # "melMass-comfy_mtb-3b07984": "python",
    # "log10-io-log10-d605f37": "python",
    # "eimenhmdt-autoresearcher-5235ee7": "python",
    # "Gage-Technologies-embedding-server-6b66d47": "python",
    # "DAMO-NLP-SG-MT-LLaMA-c72f7db": "python",
    # "paulpanwang-Cas6D-245489d": "python",
    # "ashi-ta-speechGLUE-724cf40": "python",
    # "tarsil-databasez-01b23b0": "python",
    # "K024-chatglm-q-eab6472": "python",
    # "dishb-hive-f0bf4b5": "python",
    # "Mattie-chatsnack-94305b2": "python",
    # "usecakework-async-backend-c288d0b": "python",
    # "Spawning-Inc-datadiligence-9e949d2": "python",
    # "danilonumeroso-dar-64e8631": "python",
    # "continuum-llms-chatgpt-memory-ee08ccc": "python",
    # "danyi1212-celery-insights-a742653": "python",
    # "hyp3rd-telegram-discord-bridge-24fa2fb": "python",
    # "babylm-baseline-pretraining-43acf2a": "python",
    # "f-inc-dynamic-e4036a7": "python",
    # "leandl-wvalidate-8cb9603": "python",
    # "bufbuild-protovalidate-python-2eee9ba": "python",
    # "phac-nml-rebar-aef5b97": "python",
    # "celyes-checkr-dabd705": "python",
    # "deep-diver-TFX-WandB-05c63c4": "python",
    # "irgolic-AutoPR-10e2891": "python",
    # "czczup-GPTrans-1f6f651": "python",
    # "xrcyz-dpg-swisscontrols-9412ad4": "python",
    # "aiplan4eu-UP4ROS-59c1358": "python",
    # "open-mmlab-Multimodal-GPT-9c73e47": "python",
    # "inWeb3ai-chatWeb3-cf1c933": "python",
    # "dichem-django-excel-report-686e1da": "python",
    # "yotakayama-STLCCP-edcfad4": "python",
    # "Materials-Data-Science-and-Informatics-somesy-a47ca93": "python",
    # "operand-agency-07b1076": "python",
    # "SAIC-iSmart-API-saic-python-client-29b99ad": "python",
    # "mihirh19-todo_web_app-fed9043": "python",
    # "wxian3-NeuroLens-380d68c": "python",
    # "sonic-net-sonic-platform-vpp-e8483f4": "python",
    # "gitguesser-gitguesser-297d633": "python",
    # "dory111111-Pengenuity-297d9ee": "python",
    # "microsoft-DPSDA-79f0868": "python",
    # "beidongjiedeguang-openai-forward-c2c2757": "python",
    # "AdaptChat-adapt.py-9e079c0": "python",
    # "ZJUM3-LLMEval_RCC-a731888": "python",
    # "ironwoodcall-TagTracker-bb1e3d9": "python",
    # "deepmatterltd-rdfreader-a811645": "python",
    # "SilicalNZ-TapTitans2py-0d5409d": "python",
    # "CircuitSacul-io-775ac7c": "python",
    # "valentingol-cliconfig-c772180": "python",
    # "callowayproject-bump-my-version-0cf1cb5": "python",
    # "rmihaylov-falcontune-6bd029e": "python",
    # "last-war-photoshare-fastapi-67888ff": "python",
    # "crypto-jobs-fyi-crawler-b0596e6": "python",
    # "pycob-pyvibe-1c1c138": "python",
    # "motherofcoconuts-async-dramatiq-b9512a1": "python",
    # "ch3njust1n-generative-api-a2ac928": "python",
    # "colindecourt-darod-ab4878e": "python",
    # "uezo-aiavatarkit-37d28f7": "python",
    # "tricktreat-PromptNER-3857235": "python",
    # "viper-framework-viper2-bd8aa34": "python",
    # "oriyor-reasoning-on-cots-9ae01ce": "python",
    # "jfamestad-TexasHoldemAgents-a171a13": "python",
    # "lxjmaster-ja3requests-90a33e6": "python",
    # "nyaarium-blender-nyaatools-4fc69af": "python",
    # "amazon-science-random-tma-43df305": "python",
    # "RTIInternational-teehr-2bd727d": "python",
    # "yuvalkirstain-PickScore-5fa69e8": "python",
    # "Mikanwolfe-Kuro-55d0744": "python",
    # "vectara-vectara-ingest-0a867f1": "python",
    # "Textualize-frogmouth-965b92e": "python",
    # "francoismdj-netbox-kea-dhcp-f53d9df": "python",
    # "radar-research-lab-MFGLib-7f12f9d": "python",
    # "techonomydev-django-crispy-tableselect-e2e7016": "python",
    # "20171130-llmux-249dcdb": "python",
    # "quarkslab-tritondse-9805288": "python",
    # "javiber-scrat-748926a": "python",
    # "stac-utils-stac-asset-a83c660": "python",
    # "mecene-studio-debugGpt-20e9b61": "python",
    # "PatrickKalkman-python-eda-e98886c": "python",
    # "Stardust-hyx-Instruction_Tuning-62e36d0": "python",
    # "sprite-neu-SPREAD-API-a2ee03a": "python",
    # "Genentech-walk-jump-3cfaa37": "python",
    # "huanranchen-EnergyBasedGenerativeModel-ad5989a": "python",
    # "CassioML-cassio-7953897": "python",
    # "brown-ivl-Cafi-Net-6171499": "python",
    # "Ying1123-llm-caching-multiplexing-2dc7e69": "python",
    # "Typing-Monkeys-complex-network-link-prediction-cf69190": "python",
    # "eloimoliner-BABE-777b624": "python",
    # "ddPn08-rvc-webui-c4a12a8": "python",
    # "RobertoCorti-gptravel-bcf49dd": "python",
    # "tmori-generative-agents-81cabfd": "python",
    # "microsoft-deep-language-networks-e7accd0": "python",
    # "SEIAROTg-autobean-format-2a51179": "python",
    # "algorand-conduit-bcb54fd": "python",
    # "theneonwhale-frt-photo-share-6659afb": "python",
    # "heng840-All_pipeline_Information_Extraction-e94dd96": "python",
    # "UKPLab-nlpeer-f81f4bb": "python",
    # "utiasDSL-fmpc_socp-de13764": "python",
    # "chunmeifeng-FedPR-f5c3e67": "python",
    # "imaginationtech-constrainedrandom-db5b49a": "python",
    # "entangled-entangled.py-4dcbb63": "python",
    # "bxdoan-venom-auto-da0fcfa": "python",
    # "Kamilfo-Developer-alice-sleepy-helper-skill-febf9f7": "python",
    # "obahamonde-aiofauna-67993d2": "python",
    # "ingra14m-mipnerf360-pytorch-bfc1e77": "python",
    # "fivexl-terraform-aws-sso-elevator-fd46f09": "python",
    # "s41m0n-enid-227634a": "python",
    # "jiangjiechen-uncommongen-7d1c76e": "python",
    # "Panzer-Jack-ChatGLM_VITS_For_QQ-Rob-5b11f0a": "python",
    # "brdav-cma-fdae11a": "python",
    # "diptanu-indexify-216ecf2": "python",
    # "rosemary666-chatgpt-3adfb2d": "python",
    # "graphcore-PopTransformer-1314598": "python",
    # "pitaya1001-hta-c83dc5c": "python",
    # "speedb-io-log-parser-d600b0e": "python",
    # "kiran94-prfiesta-c37e012": "python",
    # "Hxyou-IdealGPT-54f5acf": "python",
    # "dpasse-extr-f695d3c": "python",
    # "krishnaik06-Chicken-Disease-Classification-Projects-d0f5e13": "python",
    # "yarrow-id-diagrams-9cbd653": "python",
    # "voneiden-ocp-freecad-cam-4813dc9": "python",
    # "Donnype-xtdb-py-fc89588": "python",
    # "jannerm-ddpo-f0b6ca7": "python",
    # "ppoitier-sign-language-tools-46eadf9": "python",
    # "yanqingmen-ask-api-69926aa": "python",
    # "canpool-QxRibbon-4bbd7f5": "python",
    # "axelmunch-laser-tag-38f6fc0": "python",
    # "SolarisNeko-suger-python-67383eb": "python",
    # "heshuting555-PAP-FZS3D-e3fc6cb": "python",
    # "quarkslab-pastis-d790def": "python",
    # "Open-Swarm-Net-GPT-Swarm-edfddce": "python",
    # "gabacode-chatGPDP-4701532": "python",
    # "kabeer11000-autollm-53e7404":"python",
    # "libsql-libsql-client-py-484c7d3":"python",
    # "OpenGVLab-VideoMAEv2-9492db0": "python",
    # "liuzuxin-OSRL-6ede2c2": "python",
    # "knexer-ai-storyteller-86da1d3": "python",
    # "pomponchik-instld-1df14ba": "python",
    # "OpenAccess-AI-Collective-axolotl-2c37bf6": "python",
    # "gnbonney-SymLogos-08a26af": "python",
    # "solo-spice-sospice-64c941b": "python",
    # "odtuyzt-chrono-kit-923b505": "python",
    # "david-stan-dagfed-chain-0a60a23": "python",
    # "NoFish-528-encodec-pytorch-9c2f4a0": "python",
    # "hq0709-Depth-NeuS-49d93d4": "python",
    # "chrisrude-oobabot-fa234d6": "python",
    # "marcpage-pylavi-90a3e81": "python",
    # "NKI-AI-STAPLER-bf072e9": "python",
    # "JohnnyIrvin-shell-craft-26a7af7": "python",
    # "Jason-Qiu-MultiSum_model-c4c58dd": "python",
    # "esnya-lm-talkbot-f072b85": "python",
    # "smpanaro-more-ane-transformers-d5aec6f": "python",
    # "slewie-HypONIC-5b95063": "python",
    # "deadblue-py115-ecdcb93": "python",
    # "IntelligenzaArtificiale-Free-Auto-GPT-095e991": "python",
    # "appsignal-appsignal-python-5a0cfa9": "python",
    # "chunbolang-R2Net-856e1cc": "python",
    # "geoffwhittington-meshtastic-matrix-relay-ffe969f": "python",
    # "satyapravin-Deribit-Option-Arb-c6fead7": "python",
    # "amazon-science-ope-learn-action-embeddings-4ff26bf": "python",
    # "flatironinstitute-mountainsort5-3e85076": "python",
    # "reko-beep-hsr-data-c73208a": "python",
    # "kabachuha-sd-webui-text2video-20ead10": "python",
    # "AlphaDinosaur89-glang-de75a3e": "python",
    # "iuiaoin-wechat-gptbot-b379085": "python",
    # "Adeon18-Mori-Bazius-Backend-f33b8ba": "python",
    # "medley56-space_packet_parser-d94290c": "python",
    # "KTH-FlowAI-DeepReinforcementLearning_RayleighBenard2D_Control-d1a8dd6": "python",
    # "maxvanspengler-hyperbolic_learning_library-f6cfca3": "python",
    # "scottjiao-SlotGAT_ICML23-4aa4583": "python",
    # "Donkie-Spoolman-2fcfc38": "python",
    # "vetka925-llms-lora-8bit-4bit-finetuning-lit-eb1b149": "python",
    # "adrienbrignon-mkdocs-exporter-bdbd7b5": "python",
    # "thb1314-maskrcnn-tensorrt-1bafff6": "python",
    # "kit-cel-mokka-8a555d9": "python",
    # "HelsinkiUniCollab-WeatherBasedRecommender-cfd21fd": "python",
    # "CPJKU-paow-c8ead3d": "python",
    # "opticore-netbox-celery-553cbe6": "python",
    # "probcomp-LLaMPPL-56ef219": "python",
    # "Cybereason-eztw-94a0ae9": "python",
    # "bytedance-uss-0c15a08": "python",
    # "Thetacz-nautobot-plugin-device-resources-4caef01": "python",
    # "LeoMo-27-FastAPI-template-f19c7aa": "python",
    # "janvarev-OneRingTranslator-e4dab8d": "python",
    # "snu-mllab-Efficient-CNN-Depth-Compression-2828ae8": "python",
    # "LineIndent-material_design_flet-bca5bd8": "python",
    # "SindiLab-scANNA-b65b3d8": "python",
    # "awslabs-decode-answer-logical-form-08d5790": "python",
    # "ZX-Yin-ms-nerf-9009137": "python",
    # "bharatsubedi-PARseq_torch-8ffcb95": "python",
    # "maybelinot-yamx-5e304a5": "python",
    # "Josh-XT-AGiXT-828a01d": "python",
    # "EdwardLeeLPZ-PowerBEV-7ead4ce": "python",
    # "eugenos-programos-Own-language-with-LLVM-lite-c8b9e08": "python",
    # "eurobios-scb-acrocord-94aeb5e": "python",
    # "jdum-asciinema-scene-82f586d": "python",
    # "bond-anton-BDPotentiometer-872a7e2": "python",
    # "StigLidu-AutoTruss-ffb5707": "python",
    # "datasig-ac-uk-RoughPy-fbd9016": "python",
    # "YangXiaocui1215-GMP-d3cb04f": "python",
    # "ansys-pyaedt-toolkit-template-73b2fc9": "python",
    # "krishnaik06-Text-Summarization-NLP-Project-3308112": "python",
    # "leonelhs-face-shine-8f21b90": "python",
    # "CERT-EDF-generaptor-e71eb4c": "python",
    # "chrisdewa-ardilla-312a373": "python",
    # "deep-diver-PingPong-7ace26b": "python",
    # "wolfhoundgelert-xman-1da4d2d": "python",
    # "jiggy-ai-jiggybase-068b82b": "python",
    # "vladkens-twscrape-4f2ee7f": "python",
    # "remixer-dec-botality-ii-f8402d5": "python",
    # "dSupertramp-PubGPT-253ec52": "python"
    }

    models = {
        "codegen2-1B": "/mnt/silver/tanlei/hf-models/codegen2-1B_P",
        "codegen2-3_7B": "/mnt/silver/tanlei/hf-models/codegen2-3_7B_P",
        "codegen2-7B": "/mnt/silver/tanlei/hf-models/codegen2-7B_P",
        "codegen2-16B": "/mnt/silver/tanlei/hf-models/codegen2-16B_P",
        
        "starcoder2-3b": "/mnt/silver/tanlei/hf-models/starcoder2-3b",
        "starcoder2-7b": "/mnt/silver/tanlei/hf-models/starcoder2-7b",
        "starcoder2-15b": "/mnt/silver/tanlei/hf-models/starcoder2-15b",

        "DeepSeek-Coder-V2-Instruct": "/mnt/silver/tanlei/hf-models/DeepSeek-Coder-V2-Instruct",
        "DeepSeek-Coder-V2-Lite-Instruct": "/mnt/silver/tanlei/hf-models/DeepSeek-Coder-V2-Lite-Instruct",

        "CodeLlama-7b-Instruct": "/mnt/silver/tanlei/hf-models/CodeLlama-7b-Instruct-hf",
        "CodeLlama-13b-Instruct": "/mnt/silver/tanlei/hf-models/CodeLlama-13b-Instruct-hf",
        "CodeLlama-34b-Instruct": "/mnt/silver/tanlei/hf-models/CodeLlama-34b-Instruct-hf",

        "Qwen2.5-Coder-0.5B-Instruct": "/mnt/silver/tanlei/hf-models/Qwen2.5-Coder-0.5B-Instruct",
        "Qwen2.5-Coder-7B-Instruct": "/mnt/silver/tanlei/hf-models/Qwen2.5-Coder-7B-Instruct",
        "Qwen2.5-Coder-14B-Instruct": "/mnt/silver/tanlei/hf-models/Qwen2.5-Coder-14B-Instruct",
        "Qwen2.5-Coder-32B-Instruct": "/mnt/silver/tanlei/hf-models/Qwen2.5-Coder-32B-Instruct",
    }



def iterate_repository_file(base_dir, repo):
    """
    根据仓库的编程语言，生成匹配代码文件的模式，并返回所有匹配的文件路径列表。

    参数:
    base_dir (str): 仓库的基础目录。
    repo (str): 仓库的名称。

    返回:
    list: 匹配的文件路径列表。

    异常:
    NotImplementedError: 如果仓库的编程语言不支持。
    """
    # 根据仓库的编程语言，生成匹配代码文件的模式
    lang = CONSTANTS.repos_language.get(repo, "")
    if lang == "python":
        pattern = os.path.join(base_dir, repo, "**", "*.py")
    elif lang == "java":
        pattern = os.path.join(base_dir, repo, "**", "*.java")
    else:
        raise NotImplementedError(f"不支持的语言类型：{lang}")
    
    # 使用 glob 查找所有匹配路径，并过滤出实际文件
    all_paths = glob.glob(pattern, recursive=True)
    files = [path for path in all_paths if os.path.isfile(path)]
    return files


def iterate_repository_json_file(base_dir, repo):
    """
    生成匹配JSON文件的模式，并返回所有匹配的文件路径列表。

    参数:
    base_dir (str): 仓库的基础目录。
    repo (str): 仓库的名称。

    返回:
    list: 匹配的文件路径列表。
    """
    pattern = os.path.join(f'{base_dir}/{repo}', "**", "*.json")
    files = glob.glob(pattern, recursive=True)
    return files


def make_needed_dir(file_path):
    """
    创建文件路径所需的目录。

    参数:
    file_path (str): 文件路径。
    """
    dir_path = os.path.dirname(file_path)
    if not os.path.exists(dir_path):
        os.makedirs(dir_path)
    return


def load_pickle(fname):
    """
    从pickle文件中加载数据。

    参数:
    fname (str): pickle文件的路径。

    返回:
    object: 从pickle文件中加载的数据。
    """
    with open(fname, 'rb') as f:
        return pickle.load(f)


def set_default(o):
    if isinstance(o, nx.Graph):
        return nx.node_link_data(o)  # 将图结构转为字典
    elif isinstance(o, set):
        return list(o)  # 集合转列表
    elif isinstance(o, np.integer):
        return int(o)  # numpy整数转Python原生类型
    elif isinstance(o, np.floating):
        return float(o)
    raise TypeError


def dump_jsonl(obj, fname):
    """
    将对象以JSONL格式写入文件。

    参数:
    obj (object): 需要写入的对象。
    fname (str): 文件路径。
    """
    with open(fname, 'w', encoding='utf8') as f:
        for item in obj:
            f.write(json.dumps(item, default=set_default) + '\n')


def load_jsonl(fname):
    """
    从JSONL文件中加载数据。

    参数:
    fname (str): JSONL文件的路径。

    返回:
    list: 从文件中加载的对象列表。
    """
    with open(fname, 'r', encoding='utf8') as f:
        lines = []
        for line in f:
            lines.append(json.loads(line))
        return lines


def graph_to_json(obj: nx.MultiDiGraph):
    """
    将图对象转换为JSON格式。

    参数:
    obj (nx.MultiDiGraph): 图对象。

    返回:
    str: JSON格式的图数据。
    """
    return json.dumps(json_graph.node_link_data(obj), default=set_default)


def json_to_graph(json_format):
    """
    将JSON格式的数据转换为图对象。

    参数:
    json_format (str): JSON格式的图数据。

    返回:
    nx.MultiDiGraph: 图对象。
    """
    graph_js = json.loads(json_format)
    graph = json_graph.node_link_graph(graph_js)
    return graph


def tokenize(code):
    """
    对代码进行分词。

    参数:
    code (str): 代码字符串。

    返回:
    list: 分词后的标记列表。
    """
    tokenizer = CodexTokenizer()
    return tokenizer.tokenize(code)